site_name: Code without Barriers 💻💞 with Microsoft
theme:
  name: material
  # Enable features for better accessibility
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    # Responsive tables
    - content.tabs.link
    - content.tooltips
    # Make navigation more accessible
    - toc.integrate
    - toc.follow
  # Color schemes and toggle
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # Accessible fonts and sizing
  font:
    text: 
      - Comic Sans MS
      - Comic Sans
      - system-ui
      - -apple-system
      - Segoe UI
      - Roboto
      - Helvetica Neue
      - Arial
      - sans-serif
    code:
      - Cascadia Code
      - Source Code Pro
      - Roboto Mono
      - monospace
  # Improve font sizes and spacing
  font_size:
    scale: 1.15
  icon:
    logo: material/book-open-page-variant
nav:
  - Home: index.md
  - Welcome: welcome.md
  - Mindset Shift: mindset.md
  - Copilot as Teacher: copilot-teacher.md
  - Copilot as Pair Programmer: copilot-pair.md
  - Copilot as Enabler: copilot-enabler.md
  - Code Demos: demos/5ways.py
  - Wrap-Up & Resources: wrapup.md
  - Assets: assets/readme.md

  # Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/codess-aus
    - icon: fontawesome/brands/twitter
      link: https://bsky.app/profile/codess-aus.bsky.social
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/michellesandford

