site_name: Coding & Cupcakes 🍰 with Microsoft & She Codes Australia
theme:
  name: material
  palette:
    primary: purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Welcome: welcome.md
  - Mindset Shift: mindset.md
  - Copilot as Teacher: copilot-teacher.md
  - Copilot as Pair Programmer: copilot-pair.md
  - Copilot as Enabler: copilot-enabler.md
  - Code Demos: demos/5ways.py
  - Wrap-Up & Resources: wrapup.md
